version: "3.9"
services:
  react-app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    image: app:react
    container_name: react_container
    command: npm start